name: tocker
base: core20
version: '3.0'
summary: A test of interacting with the Docker snap through another snap
description: |
  This snap moves a Docker-based workflow to a snap'd environment on Ubuntu
  Core. This snap shows how one would interact with the docker snap, namely
  through a content sharing interface to gain access to the docker executable,
  along with simple scripts to make use of Docker.

grade: stable
confinement: strict

apps:
  tocker:
    command: usr/bin/tocker_run.sh
    plugs: [docker]
  ticker:
    command: usr/bin/tocker_ticker.sh
    daemon: simple
    plugs: [docker]
  tenkins1:
    command: usr/bin/tocker_jenkins1.sh
    plugs: [docker]
  tenkins2:
    command: usr/bin/tocker_jenkins2.sh
    plugs: [docker]
  tedgex:
    command: usr/bin/tocker_edgex.sh
    daemon: simple
    plugs: [docker]

parts:
  copy-script:
    plugin: dump
    source: src/

plugs:
  docker-executables:
    interface: content
    content: executables
    target: $SNAP/docker-bin
